- name: Copy config file
  copy:
    src: ../files/agent.hcl
    dest: /etc/consul.d/agent.hcl
    owner: consul
    group: consul
    mode: '0644'

- name: Copy systemd config file
  copy:
    src: ../files/consul-agent.service
    dest: /lib/systemd/system/consul-agent.service
    owner: consul
    group: consul
    mode: '0644'

- name: Start consul
  systemd:
    daemon-reload: true
    state: restarted
    name: consul-agent
    enabled: true