---
- name: Secrets | Create all secrets
  no_log: true # Do not show logs as they contain all the k8s secrets
  with_items: "{{ k8s_secrets }}"
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
      type: Opaque
      stringData: "{{ item.stringData }}"
