---
# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "release-name-minecraft-rcon"
  namespace: default
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
type: Opaque
data:
  rcon-password: "Q0hBTkdFTUUh"
---
# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "release-name-minecraft-curseforge"
  namespace: default
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
type: Opaque
data:
  cf-api-key: "Q0hBTkdFTUUh"
---
# Source: minecraft/templates/minecraft-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-minecraft
  namespace: default
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: release-name-minecraft
