minecraft:
  workloadAsStatefulSet: true
  strategyType: RollingUpdate

  minecraftServer:
    eula: true
    serviceType: LoadBalancer
    type: PAPER

  persistence:
    dataDir:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
