minecraft:
  workloadAsStatefulSet: true
  strategyType: RollingUpdate

  minecraftServer:
    eula: true
    serviceType: LoadBalancer
    type: PAPER
    pluginUrls:
      - https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
      - https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    extraPorts:
      - name: bedrock
        containerPort: 19132
        protocol: UDP
        service:
          enabled: false
        

  persistence:
    dataDir:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
