destination: https://kubernetes.default.svc
repoURL: git@github.com:VoyTechnology/homelab.git
project: infra
apps:
  longhorn:
    namespace: longhorn-system
    path: charts/longhorn
  # ---
  external-dns:
    namespace: external-dns-system
    skipNamespaceCreation: true # Managed by Ansible
    path: charts/external-dns
  monitoring:
    namespace: monitoring
    path: charts/monitoring
    helm:
      # TODO: Extract somewhere else
      domain: dub1.bednarzak.com

  ingress-external:
    namespace: ingress-external
    skipNamespaceCreation: true # Managed by Ansible
    path: charts/ingress-external
