destination: https://kubernetes.default.svc
repoURL: git@github.com:VoyTechnology/home-ansible.git
project: infra
apps:
  longhorn:
    namespace: longhorn-system
    path: charts/longhorn
  ingress-public:
    namespace: tailscale
    # Namespace is created using Ansible to allow for OAuth Secret creation.
    skipNamespaceCreation: true
    path: charts/ingress-internal
  # monitoring:
  #   namespace: monitoring
  #   path: charts/monitoring
