all:
  hosts:
    s1-nvn:
      ansible_host: 192.168.1.10
      ansible_user: root
    s2-nvn1:
      ansible_host: 192.168.1.11
      ansible_user: root
      nomad_class: disk
    s3-nvn1:
      ansible_host: 192.168.1.12
      ansible_user: root
  children:
    vault:
      hosts:
        s1-nvn:
    consul-server:
      hosts:
        s1-nvn:
    nomad-server:
      hosts:
        s1-nvn:
    consul-agent:
      hosts:
        s2-nvn1:
        s3-nvn1:
    nomad-client:
      hosts:
        s1-nvn:
        s2-nvn1:
        s3-nvn1:
    minecraft:
      hosts:
        s2-nvn1:
    frontend:
      hosts:
        s1-nvn: