---
- import_playbook: playbooks/install_basic.yml
- import_playbook: playbooks/install_consul_master.yml
- import_playbook: playbooks/install_consul_clients.yml
- import_playbook: playbooks/install_nomad_master.yml
- import_playbook: playbooks/install_nomad_clients.yml