---
# - import_playbook: playbooks/install_basic.yml
- import_playbook: playbooks/install_consul_master.yml
- import_playbook: playbooks/install_consul_clients.yml
- import_playbook: playbooks/install_nomad_master.yml
- import_playbook: playbooks/install_nomad_clients.yml
# - import_playbook: playbooks/install_adguardhome.yml

# - name: Setup Traefik
#   hosts: frontend
#   become: true
#   roles:
#   - traefik



# This is in AUR, we need to fix it
# - name: Install Vault
#   hosts: master
#   become: true
#   roles:
#   - vault


# - name: Install Minecraft
#   hosts: minecraft
#   become: true
#   roles:
#   - minecraft
