homeassistant:
  ingress:
    enabled: true
    hosts:
      - host: homeassistant.REPLACE_ME
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: homeassistant-tls
        hosts:
          - homeassistant.REPLACE_ME
  configuration:
    trusted_proxies:
      - 10.0.0.0/8 # Too much?
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
