homeassistant:
  ingress:
    enabled: true
    hosts:
      - host: homeassistant.REPLACE_ME
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
    - secretName: homeassistant-tls
      hosts:
      - homeassistant.REPLACE_ME
