homeassistant:
  hostNetwork: true
  ingress:
    enabled: true
    hosts:
      - host: homeassistant.REPLACE_ME
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: homeassistant-tls
        hosts:
          - homeassistant.REPLACE_ME
  configuration:
    enabled: true
    trusted_proxies:
      - 10.0.0.0/8 # Too much?
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

musicassistant:
  ingress:
    main:
      enabled: true
      hosts:
        - host: musicassistant.REPLACE_ME
          paths:
            - path: /
              pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: musicassistant-tls
          hosts:
            - musicassistant.REPLACE_ME
  persistence:
    # enabled: true
    config:
      enabled: true

  metrics:
    enabled: true
    prometheusRule:
      enabled: true
