homeassistant:
  hostNetwork: true
  # Extra permissions needed for Zigbee Dongle
  securityContext:
    privileged: true

  ingress:
    enabled: true
    hosts:
      - host: homeassistant.REPLACE_ME
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: homeassistant-tls
        hosts:
          - homeassistant.REPLACE_ME
  configuration:
    enabled: true
    trusted_proxies:
      - 10.0.0.0/8 # Too much?
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

matter:
  # Can this be hardcoded? Will we need to do some funky lookups?
  networkInterface: enp6s0
  persistence:
    size: 10Gi
    storageClassName: longhorn

musicassistant:
  persistence:
    storageClass: longhorn
