- name: Install base packages
  ansible.builtin.apt:
    name:
    - htop
    - neovim
    - unzip
    - docker.io
    - git
    - open-iscsi
    - python3-pip
    - python3-kubernetes

- name: Setup installation folders
  file:
    path: /usr/local/bin
    state: directory

- name: Install helm if not exists
  import_tasks: helm.yml

- name: Enable Docker service
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
