- name: Install base packages
  pacman:
    name:
    - htop
    - vim
    - unzip
    - docker
    - git

- name: Enable Docker service
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
