extraObjects:
  clusterSecretStore:
    apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: cluster-secrets
    spec:
      provider:
        kubernetes:
          server:
            url: "https://kubernetes.default.svc"
            caProvider:
              type: ConfigMap
              name: kube-root-ca.crt
              key: ca.crt
              namespace: kube-system
          auth:
            serviceAccount:
              name: externalsecrets-external-secrets
