---
k3s_version: v1.30.0+k3s1
helm_version: v3.15.0
ansible_user: root
systemd_dir: /etc/systemd/system
master_ip: 100.122.232.149 # Hardcoded from tailscale, assuming to never change
extra_server_args: ""
extra_agent_args: ""
