# Shared cluster values
---
# Cluster domain is the top level configuration from which all other URLs are created
cluster_domain: "dub1.bednarzak.com"
cluster_name: "dub1"

# Namespaces which are used across the cluster
monitoring_namespace: "monitoring"

# Minio storage namespace
minio_namespace: "minio"

# List of infra namespaces to create which are pre-created or used in Ansible
infra_namespaces:
- "{{ internal_ingress_namespace }}"
- "{{ argocd_k8s_namespace }}"
- "{{ cert_manager_namespace }}"
- "{{ cloudflare_external_dns_namespace }}"
- "{{ external_ingress_namespace }}"
- "{{ monitoring_namespace }}"
- "{{ minio_namespace }}"
