{{- if $.Values.mimir.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-{{ tpl $.Values.cluster_name $ }}-metrics-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "true"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: {{ tpl $.Values.cluster_name $ }}
      type: prometheus
      access: proxy
      orgId: 1
      url: http://metrics.{{ tpl $.Values.domain $ }}/prometheus
      basicAuth: false
      editable: false
      jsonData:
        oauthPassThru: true
        httpHeaderName1: "X-Scope-OrgID"
        httpHeaderValue1: "fake"
{{- end }}
