---
- name: Ingress Internal | Deploy Internal Ingress
  kubernetes.core.helm:
    # state: absent
    name: nginx-ingress-internal
    force: true
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ internal_ingress_nginx_chart_version }}"
    release_namespace: "{{ internal_ingress_namespace }}"
    update_repo_cache: true
    values:
      fullnameOverride: internal
      controller:
        name: internal
        service:
          loadBalancerClass: tailscale
          annotations:
            tailscale.com/hostname: "{{ cluster_name }}-internal"
        electionID: internal-ingress-controller-leader
        ingressClass: internal
        ingressClassResource:
          name: internal
          controllerValue: k8s.io/internal-ingress-nginx
        allowSnippetAnnotations: true
        extraVolumeMounts:
        - name: cache-dir
          mountPath: /var/run/cache
        extraVolumes:
        - name: cache-dir
          emptyDir: {}
