{{- if .Values.matterhub.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-matter-hub
  labels:
    app.kubernetes.io/name: home-assistant-matter-hub
    app.kubernetes.io/component: matter-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant-matter-hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant-matter-hub
        app.kubernetes.io/component: matter-hub
    spec:
      # Matter protocol requires host networking for mDNS and IPv6
      hostNetwork: true
      # Configure DNS to use cluster DNS while in host network mode
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "10.43.0.10"  # CoreDNS service IP (default k3s)
        searches:
          - "default.svc.cluster.local"
          - "svc.cluster.local" 
          - "cluster.local"
        options:
          - name: "ndots"
            value: "2"
          - name: "edns0"
      {{- with .Values.matterhub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: matter-hub
        image: {{ .Values.matterhub.image.name }}
        imagePullPolicy: {{ .Values.matterhub.image.pullPolicy }}
        env:
        - name: HAMH_HOME_ASSISTANT_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.matterhub.homeAssistant.accessTokenSecret.name }}
              key: url
        - name: HAMH_HOME_ASSISTANT_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.matterhub.homeAssistant.accessTokenSecret.name }}
              key: token
        - name: HAMH_LOG_LEVEL
          value: {{ .Values.matterhub.logLevel | quote }}
        - name: HAMH_HTTP_PORT
          value: {{ .Values.matterhub.httpPort | quote }}
        {{- if .Values.matterhub.mdnsNetworkInterface }}
        - name: HAMH_MDNS_NETWORK_INTERFACE
          value: {{ .Values.matterhub.mdnsNetworkInterface | quote }}
        {{- end }}
        {{- if .Values.matterhub.httpIpWhitelist }}
        - name: HAMH_HTTP_IP_WHITELIST
          value: {{ join "," .Values.matterhub.httpIpWhitelist | quote }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.matterhub.httpPort }}
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          {{- toYaml .Values.matterhub.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: home-assistant-matter-hub-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-matter-hub-data
  labels:
    app.kubernetes.io/name: home-assistant-matter-hub
    app.kubernetes.io/component: matter-hub
spec:
  accessModes:
    - {{ .Values.matterhub.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.matterhub.persistence.size }}
  {{- if .Values.matterhub.persistence.storageClassName }}
  storageClassName: {{ .Values.matterhub.persistence.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-matter-hub
  labels:
    app.kubernetes.io/name: home-assistant-matter-hub
    app.kubernetes.io/component: matter-hub
spec:
  type: {{ .Values.matterhub.service.type }}
  ports:
  - port: {{ .Values.matterhub.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: home-assistant-matter-hub
{{- if .Values.matterhub.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-matter-hub
  labels:
    app.kubernetes.io/name: home-assistant-matter-hub
    app.kubernetes.io/component: matter-hub
  {{- with .Values.matterhub.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.matterhub.ingress.className }}
  ingressClassName: {{ .Values.matterhub.ingress.className }}
  {{- end }}
  {{- if .Values.matterhub.ingress.tls }}
  tls:
    {{- range .Values.matterhub.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.matterhub.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: home-assistant-matter-hub
                port:
                  number: {{ $.Values.matterhub.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
