apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/voytechnology/homelab.git
      revision: HEAD
      files:
      - path: "argo/clusters/*.yaml"
      values:
        targetRevision: HEAD

  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      name: '{{ .cluster }}-monitoring'
      namespace: argocd
      labels:
        argocd.argoproj.io/application-set-name: "monitoring"
    spec:
      destination:
        namespace: monitoring
        server: '{{ .server }}'
      project: apps
      syncPolicy:
        automated:
          prune: false
          selfHeal: true

        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 30m
      revisionHistoryLimit: 3
      sources:

      - repoURL: https://github.com/voytechnology/homelab.git
        targetRevision: '{{ .values.targetRevision }}'
        path: argo/apps/monitoring
        helm:
          releaseName: monitoring
          ignoreMissingValueFiles: true
          valueFiles:
          # Optional value overrides in order of least to most precedence.
          - 'argo/apps/monitoring/{{ .cluster }}.values.yaml'
          valuesObject:
            grafana:
              ingress:
                hosts:
                - grafana.{{ .domain }}
                tls:
                - secretName: grafana-tls
                  hosts:
                  - grafana.{{ .domain }}
              grafana.ini:
                server:
                  domain: grafana.{{ .domain }}
                  root_url: https://grafana.{{ .domain }}
            mimir:
              ingress:
                hosts:
                - metrics.{{ .domain }}
                tls:
                - secretName: mimir-tls
                  hosts:
                  - metrics.{{ .domain }}


      
