defaultEntyPoints: [https]

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  traefik:
    address: ":8081"

providers:
  consulCatalog:
    endpoint:
      address: "http://192.168.1.10:8500"

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  le:
    acme:
      email: "voy@razoft.net"
      storage: "acme.json"
      httpChallenge:
        entrypoint: http

metrics:
  prometheus: {}