- name: Create Config dir
  file:
    path: /etc/traefik
    state: directory
    mode: 0700

- name: Create Data dir
  file:
    path: /opt/traefik
    state: directory
    mode: 0700

- name: Copy config file
  template:
    src: ../files/traefik.yaml
    dest: /etc/traefik/traefik.yaml
    mode: '0644'

- name: Copy systemd config file
  copy:
    src: ../files/traefik.service
    dest: /lib/systemd/system/traefik.service
    mode: '0644'

- name: Download Traefik (amd64)
  when: ansible_architecture == "x86_64"
  unarchive:
    remote_src: true
    src: https://github.com/containous/traefik/releases/download/v2.1.1/traefik_v2.1.1_linux_amd64.tar.gz
    dest: /opt/traefik

- name: Download Traefik (arm)
  when: ansible_architecture == "armv7l"
  unarchive:
    remote_src: true
    src: https://github.com/containous/traefik/releases/download/v2.1.1/traefik_v2.1.1_linux_armv7.tar.gz
    dest: /opt/traefik

- name: Download Traefik (arm64)
  when: ansible_architecture == "aarch64"
  unarchive:
    remote_src: true
    src: https://github.com/containous/traefik/releases/download/v2.1.1/traefik_v2.1.1_linux_arm64.tar.gz
    dest: /opt/traefik

- name: Start traefik
  systemd:
    daemon-reload: true
    state: restarted
    name: traefik
    enabled: true