all:
  vars:
    # Consul variables
    consul_version: 1.12.2
    consul_dc: dub1
    consul_dns_recursors:
    - 100.100.100.100 # Tailscale
    consul_servers:
    - 100.65.238.29 # s1-dub1, DNS doesn't want to work.

    # Nomad Variables
    nomad_version: 1.3.1
    nomad_region: eu-west
    nomad_dc: dub1

  children:
    s1-dub1:
      hosts:
        s1-dub1.razoft.com.beta.tailscale.net:
          ansible_user: root
    s2-dub1:
      hosts:
        s2-dub1.razoft.com.beta.tailscale.net:
          ansible_user: root
    
    leaders:
      children:
        s1-dub1:
    workers:
      children:
        s1-dub1:
        s2-dub1:
    consul-server:
      children:
        leaders:
    nomad-server:
      children:
        leaders:
    nomad-clients:
      children:
        workers:
    mediaserver:
      children:
        s1-dub1:
