external-dns:
  provider: cloudflare
  policy: sync
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret
          key: token
  extraArgs:
    - "--annotation-filter=dns.kubernetes.io/exclude notin (true)"
