external-dns:
  provider: cloudflare
  syncPolicy: sync
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret
          key: token
  extraArgs:
    - '--annotation-filter="external-dns.alpha.kubernetes.io/exclude notin (true)"'
