nameOverride: monitoring
kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
      - grafana.dub1.bednarzak.com
      tls:
      - secretName: grafana-tls
        hosts: grafana.dub1.bednarzak.com
