# Temporarily disable everything other than grafana
grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - grafana.dub1.bednarzak.com
    ingressClassName: internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.dub1.bednarzak.com
  grafana.ini:
    auth.proxy:
      enabled: true
      header_name: X-FORWARDED-EMAIL
      header_property: email
      headers: "Email:X-FORWARDED-EMAIL Name:X-FORWARDED-USER"
mimir:
  enabled: false
tempo:
  enabled: false
loki:
  enabled: false
