kube-prometheus-stack:
  nameOverride: monitoring
  grafana:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - grafana.dub1.bednarzak.com
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.dub1.bednarzak.com
