# Temporarily disable everything other than grafana
grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - grafana.dub1.bednarzak.com
    ingressClassName: internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.dub1.bednarzak.com
  grafana.ini:
    users:
      allow_sign_up: false
      auto_assign_org: true
      auto_assign_org_role: Editor
    auth:
      disable_login_form: true
    auth.basic:
      enabled: false
    auth.proxy:
      enabled: true
      header_name: X-FORWARDED-EMAIL
      header_property: email
      headers: "Email:X-FORWARDED-EMAIL Name:X-FORWARDED-USER"
      auto_sign_up: true
mimir:
  enabled: false
tempo:
  enabled: false
loki:
  enabled: false
