# Temporarily disable everything other than grafana
lgtm-distributed:
  grafana:
    enabled: false
    ingress:
      enabled: true
      hosts:
      - grafana.dub1.bednarzak.com
      ingressClassName: internal
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.dub1.bednarzak.com
  mimir:
    enabled: false
  tempo:
    enabled: false
  loki:
    enabled: false

grafana:
  enabled: false
