# Use the same namespace as openfaas itself for simplicity
# Whow knows is this a good idea or not
functionNamespace: openfaas

extraObjects:
  podMonitor:
    apiVersion: monitoring.coreos.com/v1
    kind: PodMonitor
    metadata:
      name: openfaas
    spec:
      namespaceSelector:
        matchNames:
          - openfaas
      selector:
        matchLabels: {}  # Match all pods
      podMetricsEndpoints:
        - port: metrics  # Most OpenFaaS components expose on 'metrics'
          interval: 15s
          path: /metrics
