- name: Copy config file
  copy:
    src: ../files/server.hcl
    dest: /etc/consul.d/server.hcl
    owner: consul
    group: consul
    mode: '0644'

- name: Copy systemd config file
  template:
    src: ../files/consul-server.service
    dest: /lib/systemd/system/consul-server.service
    owner: consul
    group: consul
    mode: '0644'

- name: Start consul
  systemd:
    daemon-reload: true
    state: restarted
    name: consul-server
    enabled: true