- name: Create nomad group
  group:
    name: nomad
    state: present

- name: Create nomad user
  user:
    name: nomad
    group: nomad
    state: present

- name: Create Config dir
  file:
    path: /etc/nomad.d
    state: directory
    owner: nomad
    group: nomad
    mode: 0700

- name: Create Data dir
  file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
    mode: 0700

- name: Create CNI Plugins Directory
  file:
    path: /opt/cni/bin
    state: directory
    owner: nomad
    group: nomad
    mode: 0700

################################################################################

- name: Download Nomad (amd64)
  when: ansible_architecture == "x86_64"
  unarchive:
    remote_src: true
    src: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip
    dest: /opt/nomad
    owner: nomad
    group: nomad

- name: Download Nomad (arm)
  when: ansible_architecture == "armv7l"
  unarchive:
    remote_src: true
    src: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_arm.zip
    dest: /opt/nomad
    owner: nomad
    group: nomad

- name: Download Nomad (arm64)
  when: ansible_architecture == "aarch64"
  unarchive:
    remote_src: true
    src: https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_arm64.zip
    dest: /opt/nomad
    owner: nomad
    group: nomad

################################################################################

- name: Download CNI Plugins (amd64)
  when: ansible_architecture == "x86_64"
  unarchive:
    remote_src: yes
    src: https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-arm64-v0.8.6.tgz
    dest: /opt/cni/bin
    owner: nomad
    group: nomad

- name: Download CNI Plugins (arm)
  when: ansible_architecture == "armv7l"
  unarchive:
    remote_src: yes
    src: https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-arm-v0.8.6.tgz
    dest: /opt/cni/bin
    owner: nomad
    group: nomad

- name: Download CNI Plugins (arm64)
  when: ansible_architecture == "aarch64"
  unarchive:
    remote_src: yes
    src: https://github.com/containernetworking/plugins/releases/download/v0.8.6/cni-plugins-linux-arm64-v0.8.6.tgz
    dest: /opt/cni/bin
    owner: nomad
    group: nomad

################################################################################

- name: Setup routing file
  template:
    src: ../files/nomad-consul-connect.conf
    dest: /etc/sysctl.d/nomad-consul-connect.conf
    owner: root
    group: root
    mode: 0644

- name: Setup routing environment
  shell: |
    echo 1 > /proc/sys/net/bridge/bridge-nf-call-arptables &&
    echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables &&
    echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
  