{{- range $name, $app := $.Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
spec:
  project: {{ default $app.project $.Values.project }}
  destination:
    namespace: {{ $app.namespace }}
    server: https://kubernetes.default.svc
  source:
    path: {{ $app.path }}
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    {{- if $app.helm }}
    helm:
      {{- if $app.helm.values }}
      values: |
        {{ tpl (toYaml $app.helm.values) $ }}
      {{- end }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- if $app.ignoreDifferences }}
  ignoreDifferences:
    {{ toYaml $app.ignoreDifferences | indent 4 }}
  {{- end }}
---
{{- if not $app.skipNamespaceCreation }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $app.namespace }}
---
{{- end }}
{{- end }}
