apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  rules:
  - host: longhorn.dub1.bednarzak.com
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: longhorn-frontend
              port:
                number: 80
