- name: Create folder
  file:
    path: /opt/adguardhome
    state: directory
    mode: '0644'

- name: Download adguardhome (amd64)
  when: ansible_architecture == "x86_64"
  unarchive:
    remote_src: true
    src: https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.100.8/AdGuardHome_linux_amd64.tar.gz
    dest: /opt/adguardhome

- name: Download adguardhome (arm)
  when: ansible_architecture == "armv7l"
  unarchive:
    remote_src: true
    src: https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.100.8/AdGuardHome_linux_arm.tar.gz
    dest: /opt/adguardhome

- name: Download adguardhome (arm64)
  when: ansible_architecture == "aarch64"
  unarchive:
    remote_src: true
    src: https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.100.8/AdGuardHome_linux_arm64.tar.gz
    dest: /opt/adguardhome

- name: Copy config file
  copy:
    src: ../files/AdGuardHome.yaml
    mode: '0644'
    dest: /opt/adguardhome/AdGuardHome/AdGuardHome.yaml

- name: Copy systemd config file
  copy:
    src: ../files/adguardhome.service
    mode: '0644'
    dest: /lib/systemd/system/adguardhome.service

- name: Start Adguard Home
  systemd:
    daemon-reload: true
    state: restarted
    name: adguardhome
    enabled: true