apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: donetick-data-pvc
  labels:
    app.kubernetes.io/name: donetick
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
