---
- name: cert-manager | Add Helm Repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: cert-manager | Deploy Helm Chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ cert_manager_version }}"
    release_namespace: "{{ cert_manager_namespace }}"
    update_repo_cache: true
    values:
      installCRDs: true
      webhook:
        networkPolicy:
          enabled: true
      extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53
      ingressShim:
        defaultIssuerName: letsencrypt
        defaultIssuerKind: ClusterIssuer

- name: cert-manager | Cloudflare Issuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt
        namespace: "{{ cert_manager_namespace }}"
      spec:
        acme:
          email: "{{ cloudflare_email }}"
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
          - dns01:
              cloudflare:
                email: "{{ cloudflare_email }}"
                apiKeySecretRef:
                  name: cloudflare-secret
                  key: token
