---
- name: Setup Namespaces
  import_tasks: namespaces.yml
  tags: k8s_namespaces

- name: Setup Secrets
  import_tasks: secrets.yml
  tags: k8s_secrets

- name: Setup Cert Manager
  import_tasks: cert_manager.yml
  tags: k8s_cert_manager

- name: Setup dex
  import_tasks: dex.yml
  tags: k8s_dex

- name: Setup internal ingresses
  import_tasks: ingress/main.yml
  tags: k8s_ingress

- name: Setup Argo
  import_tasks: argocd.yml
  tags: k8s_argo

- name: Setup Extra CRDs
  import_tasks: crds.yml
  tags: k8s_crds
