longhorn:
  ingress:
    enabled: true
    host: longhorn.dub1.bednarzak.com
  csi:
    # Specific to k3s installations.
    kubeletRootDir: /var/lib/kubelet
  persistence:
    # Use 2 replicas as its unlikely we will have more storage anytime soon
    defaultClassReplicaCount: 2 
