---
# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "release-name-minecraft-rcon"
  namespace: default
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
type: Opaque
data:
  rcon-password: "Q0hBTkdFTUUh"
---
# Source: minecraft/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "release-name-minecraft-curseforge"
  namespace: default
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
type: Opaque
data:
  cf-api-key: "Q0hBTkdFTUUh"
---
# Source: minecraft/templates/extra-list.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-config
data:
  floodgate.yml: |
    key-file-name: key.pem

    # Floodgate prepends a prefix to bedrock usernames to avoid conflicts
    # However, certain conflicts can cause issues with some plugins so this prefix is configurable using the property below
    # It is recommended to use a prefix that does not contain alphanumerical to avoid the possibility of duplicate usernames.
    username-prefix: ""

    replace-spaces: true

    disconnect:
      # The disconnect message Geyser users should get when connecting
      # to the server with an invalid key
      invalid-key: Please connect through the official Geyser
      # The disconnect message Geyser users should get when connecting
      # to the server with the correct key but not with the correct data format
      invalid-arguments-length: Expected {} arguments, got {}. Is Geyser up-to-date?

    # Configuration for player linking
    player-link:
      # Whether to enable the linking system. Turning this off will prevent
      # players from using the linking feature even if they are already linked.
      enabled: true

      # Whether to require a linked account in order to be able to join the server.
      require-link: false

      # Set the following option to true when you want to host your own linking database.
      # -> This can work in addition to global linking.
      # Note that you have to install a linking database implementation before enabling this, because
      # it'll cause errors otherwise.
      enable-own-linking: false

      # The following three options only apply when 'enable-own-linking' is set to 'true'

      # Whether to allow the use of /linkaccount and /unlinkaccount
      # You can also use allow specific people to use the commands using the
      # permissions floodgate.command.linkaccount and floodgate.command.unlinkaccount.
      # This is only for linking, already connected people will stay connected
      allowed: true
      # The amount of time until a link code expires in seconds.
      link-code-timeout: 300
      # The player linking database type you want to use. This option is only used when there
      # are multiple database implementations found in the configuration directory.
      type: sqlite

      # Whether to enable global linking. Global Linking is a central server where people can link their
      # accounts (Java and Bedrock) and join on servers that have Global Linking enabled. The goal of
      # Global Linking is to make linking easier by not having to link your accounts on every server.
      # -> Your server-specific linking database will have priority over global linking.
      # Global Linking should normally only be disabled when you don't have internet access or when
      # you have limited internet access.
      enable-global-linking: true

    metrics:
      enabled: true
      uuid: e8b4417b-ff07-4522-a765-7f7f53328b39

    # Do not change this
    config-version: 3
  bluemap.conf: |
    accept-download: true
---
# Source: minecraft/templates/minecraft-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-minecraft
  namespace: default
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
  annotations:
    {}
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: release-name-minecraft
---
# Source: minecraft/templates/rcon-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "release-name-minecraft-rcon"
  namespace: default
  annotations:
    {}
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
spec:
  type: ClusterIP
  ports:
  - name: rcon
    port: 25575
    targetPort: rcon
    protocol: TCP
  selector:
    app: release-name-minecraft
---
# Source: minecraft/templates/deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-minecraft
  namespace: default
  labels:
    app: release-name-minecraft
    chart: minecraft-4.26.1
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: "minecraft"
    app.kubernetes.io/instance: release-name-minecraft
    app.kubernetes.io/version: 4.26.1
spec:
  replicas: 1
  serviceName: release-name-minecraft
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: release-name-minecraft
  template:
    metadata:
      labels:
        app: release-name-minecraft
        app.kubernetes.io/name: "minecraft"
        app.kubernetes.io/instance: release-name-minecraft
        app.kubernetes.io/version: 4.26.1
    spec:
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: release-name-minecraft
        image: "itzg/minecraft-server:latest"
        imagePullPolicy: Always
        tty: true
        stdin: true
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          exec:
            command:
            - mc-health
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - mc-health
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 20
          successThreshold: 1
          timeoutSeconds: 1
        env:
        - name: EULA
          value: "true"
        - name: TYPE
          value: "PAPER"
        - name: VERSION
          value: "LATEST"
        - name: DIFFICULTY
          value: "easy"
        - name: MAX_BUILD_HEIGHT
          value: "320"
        - name: MODE
          value: "survival"
        - name: MOTD
          value: "Welcome to Minecraft on Kubernetes!"
        - name: LEVEL_TYPE
          value: "DEFAULT"
        - name: LEVEL
          value: "world"
        - name: PLUGINS
          value: "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot,https://github.com/ViaVersion/ViaVersion/releases/download/5.2.1/ViaVersion-5.2.1.jar,https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.7/bluemap-5.7-paper.jar"
        - name: MODRINTH_DOWNLOAD_DEPENDENCIES
          value: "none"
        - name: MEMORY
          value: "1024M"
        - name: ENABLE_RCON
          value: "true"
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-minecraft-rcon
              key: rcon-password
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: release-name-minecraft-curseforge
              key: cf-api-key
        - name: CF_PARALLEL_DOWNLOADS
          value: "4"

        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25575
          protocol: TCP
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: datadir
          mountPath: /data
        - name: backupdir
          mountPath: /backups
          readOnly: true
        - mountPath: /data/plugins/floodgate/config.yml
          name: extra-config
          subPath: floodgate.yml
        - mountPath: /data/plugins/BlueMap/core.conf
          name: extra-config
          subPath: bluemap.conf
        - mountPath: /backups
          name: backups
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      - name: release-name-minecraft-mc-backup
        image: "itzg/mc-backup:latest"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: SRC_DIR
          value: "/data"
        - name: BACKUP_NAME
          value: "world"
        - name: INITIAL_DELAY
          value: "2m"
        - name: BACKUP_INTERVAL
          value: "24h"
        - name: PRUNE_BACKUPS_DAYS
          value: "7"
        - name: PAUSE_IF_NO_PLAYERS
          value: "false"
        - name: SERVER_PORT
          value: "25565"
        - name: RCON_HOST
          value: "localhost"
        - name: RCON_PORT
          value: "25575"
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-minecraft-rcon
              key: rcon-password
        - name: RCON_RETRIES
          value: "5"
        - name: RCON_RETRY_INTERVAL
          value: "10s"
        - name: EXCLUDES
          value: "*.jar,cache,logs"
        - name: BACKUP_METHOD
          value: "tar"
        - name: DEST_DIR
          value: "/backups"
        - name: LINK_LATEST
          value: "false"
        - name: TAR_COMPRESS_METHOD
          value: "gzip"
        - name: ZSTD_PARAMETERS
          value: "-3 --long=25 --single-thread"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: datadir
          mountPath: /data
          readOnly: true
        - name: backupdir
          mountPath: /backups
        - mountPath: /data/plugins/floodgate/config.yml
          name: extra-config
          subPath: floodgate.yml
        - mountPath: /data/plugins/BlueMap/core.conf
          name: extra-config
          subPath: bluemap.conf
        - mountPath: /backups
          name: backups
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: backupdir
        emptyDir: {}
      - configMap:
          name: extra-config
        name: extra-config
      - name: backups
        nfs:
          path: /nvme/minecraft/backups
          server: s1-dub1
  volumeClaimTemplates:
    - metadata:
        name: datadir
        labels:
          app: release-name-minecraft
          chart: minecraft-4.26.1
          release: "release-name"
          heritage: "Helm"
          app.kubernetes.io/name: "minecraft"
          app.kubernetes.io/instance: release-name-minecraft
          app.kubernetes.io/version: 4.26.1
        annotations:
          volume.alpha.kubernetes.io/storage-class: default
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "20Gi"
