apiVersion: v2
name: monitoring
description: Monitoring Metachart
version: 0.0.1
dependencies:
  - name: grafana
    alias: grafana
    condition: grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: "^8.11.0"
  - name: tempo
    alias: tempo
    condition: tempo.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^1.19.0"
  - name: alloy
    condition: alloy.enabled
    repository: https://grafana.github.io/helm-charts
    version: "0.12.5"
  - name: prometheus-node-exporter
    condition: prometheus-node-exporter.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: "4.45.0"
