apiVersion: v2
name: monitoring
description: Monitoring Metachart
version: 0.0.1
dependencies:
  - name: prometheus-operator-crds
    repository: https://prometheus-community.github.io/helm-charts
    version: "^13.0.2"
  - name: grafana
    alias: grafana
    condition: grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: "^8.4.4"
  - name: loki
    alias: loki
    condition: loki.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^6.10.0"
  - name: mimir-distributed
    alias: mimir
    condition: mimir.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^5.4.0"
  - name: tempo
    alias: tempo
    condition: tempo.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^1.10.3"
  - name: alloy
    condition: alloy.enabled
    repository: https://grafana.github.io/helm-charts
    version: "0.6.0"
  - name: oncall
    condition: oncall.enabled
    repository: https://grafana.github.io/helm-charts
    version: "1.8.12"
