apiVersion: v2
name: monitoring
description: Monitoring Metachart
version: 0.0.1
dependencies:
  - name: alloy
    condition: alloy.enabled
    repository: https://grafana.github.io/helm-charts
    version: "0.12.6"
  - name: prometheus-node-exporter
    condition: prometheus-node-exporter.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: "4.45.0"
