# Override the domains
grafana:
  ingress:
    hosts:
    - grafana.dub1.bednarzak.com
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.dub1.bednarzak.com
  grafana.ini:
    server:
      domain: grafana.dub1.bednarzak.com
      root_url: https://grafana.dub1.bednarzak.com
