extraObjects:
  grafanaCloudExternalSecret:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: grafana-cloud
      namespace: monitoring
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secrets
      target:
        name: grafana-cloud
        creationPolicy: Owner
      data:
        # Map each key from the source Secret directly to the target secret
        - secretKey: token
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_token
        - secretKey: remote-config-url
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_remote_config_url
        - secretKey: metrics-url
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_metrics_url
        - secretKey: logs-url
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_logs_url
