extraObjects:
  grafanaCloudExternalSecret:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: grafana-cloud
      namespace: monitoring
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secrets
      target:
        name: grafana-cloud
        creationPolicy: Owner
        template:
          type: Opaque
          data:
            token: "{{ .token }}"
            remote-config-url: "{{ .remote_config_url }}"
            metrics-url: "{{ .metrics_url }}"
            logs-url: "{{ .logs_url }}"
      data:
        # Map each key from the source Secret to match expected environment variables
        - secretKey: token
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_token
        - secretKey: remote_config_url
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_remote_config_url
        - secretKey: metrics_url
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_metrics_url
        - secretKey: logs_url
          remoteRef:
            key: shared-secrets
            property: grafana_cloud_logs_url
