# Temporarily disable everything other than grafana
domain: REPLACE_ME

grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - grafana.REPLACE_ME
    ingressClassName: internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/configuration-snippet: |
          auth_request_set $user             $upstream_http_x_auth_request_user;
          auth_request_set $email            $upstream_http_x_auth_request_email;
          proxy_set_header X-FORWARDED-EMAIL $email;
          proxy_set_header X-FORWARDED-NAME  $user;
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.REPLACE_ME
  grafana.ini:
    server:
      domain: https://REPLACE_ME
      root_url: REPLACE_ME
    users:
      allow_sign_up: false
      auto_assign_org: true
      # TODO: Reduce it once we have more users
      auto_assign_org_role: Admin
      allow_assign_grafana_admin: true
    auth:
      disable_login_form: true
      oauth_auto_login: true
    auth.basic:
      enabled: false
    auth.proxy:
      enabled: true
      header_name: X-FORWARDED-EMAIL
      header_property: email
      headers: "Email:X-FORWARDED-EMAIL Name:X-FORWARDED-USER"
      auto_sign_up: true
  plugins:
    - grafana-oncall-app

mimir:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: internal
   # Low traffic home clustes, no need for more than 1 replica and there are probably no zones.
   # downtime on upgrade is tolerated
  ingester:
    replicas: 1
    zoneAwareReplication:
      enabled: false
  querier:
    replicas: 1

tempo:
  enabled: false
loki:
  enabled: false
alloy:
  enabled: false
