# Temporarily disable everything other than grafana
domain: REPLACE_ME

grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - grafana.REPLACE_ME
    # ingressClassName: internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.REPLACE_ME
  grafana.ini:
    server:
      domain: https://REPLACE_ME
      root_url: REPLACE_ME
    users:
      allow_sign_up: false
      auto_assign_org: true
      # TODO: Reduce it once we have more users
      auto_assign_org_role: Admin
      allow_assign_grafana_admin: true
    auth:
      oauth_auto_login: true
    auth.generic_oauth:
      name: Dex
      enabled: true
      client_id: $__file{/etc/secrets/dex_oauth/client_id}
      client_secret: $__file{/etc/secrets/dex_oauth/client_secret}
    auth.basic:
      enabled: false
  extraSecretMounts:
    - name: dex-oauth
      secretName: grafana-dex-oauth-secret
      defaultMode: 0440
      mountPath: /etc/secrets/dex_oauth
      readOnly: true
  # Disable as its not currently working
  # plugins:
  #   - grafana-oncall-app

mimir:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  # Low traffic home clustes, no need for more than 1 replica and there are probably no zones.
  # downtime on upgrade is tolerated
  ingester:
    replicas: 1
    zoneAwareReplication:
      enabled: false
  querier:
    replicas: 1

tempo:
  enabled: false
loki:
  enabled: false
alloy:
  enabled: false
