# Temporarily disable everything other than grafana
domain: REPLACE_ME
cluster_name: REPLACE_ME

grafana:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana.REPLACE_ME
    ingressClassName: internal-shared # Auth using Dex, but we want to share the instance
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.REPLACE_ME
  grafana.ini:
    server:
      domain: https://REPLACE_ME
      root_url: REPLACE_ME
    users:
      allow_sign_up: false
      auto_assign_org: true
      # TODO: Reduce it once we have more users
      auto_assign_org_role: Admin
      allow_assign_grafana_admin: true
    auth:
      oauth_auto_login: true
    auth.generic_oauth:
      name: Dex
      enabled: true
      client_id: $__file{/etc/secrets/dex_oauth/client_id}
      client_secret: $__file{/etc/secrets/dex_oauth/client_secret}
      scopes: openid email profile groups offline_access
      auth_url: https://login.REPLACE_ME/auth
      token_url: https://login.REPLACE_ME/token
      api_url: https://login.REPLACE_ME/userinfo
    auth.basic:
      enabled: false
  extraSecretMounts:
    - name: dex-oauth
      secretName: grafana-dex-oauth-secret
      defaultMode: 0440
      mountPath: /etc/secrets/dex_oauth
      readOnly: true
  sidecar:
    dashboards:
      enabled: true
      labelValue: "true"
    datasources:
      enabled: true
      labelValue: "true"
  # Disable as its not currently working
  plugins:
    - grafana-oncall-app

mimir:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: internal-login
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  # Low traffic home clustes, no need for more than 1 replica and there are probably no zones.
  # downtime on upgrade is tolerated
  ingester:
    replicas: 2
    zoneAwareReplication:
      enabled: false
  querier:
    replicas: 2

tempo:
  enabled: false
loki:
  enabled: false
alloy:
  enabled: false

oncall:
  enabled: true
  base_url: oncall.REPLACE_ME
  externalGrafana:
    url: https://grafana.REPLACE_ME
  ingress:
    enabled: true
    className: internal
    annotations: null # Clear the annotations because the chart is stupid
    tls:
      - secretName: oncall-tls # Follow our own conventions
        hosts:
          - "{{ $.Values.oncall.base_url }}"

  database:
    type: postgresql

  migrate:
    useHook: true
    annotations:
      argocd.argoproj.io/hook: PostSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded

  postgresql:
    enabled: true

  # Disable the default stuff that is not needed
  ingress-nginx:
    enabled: false
  cert-manager:
    enabled: false
  grafana:
    enabled: false
  prometheus:
    enabled: false
  mariadb:
    enabled: false
