apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguardhome
  labels:
    app: adguardhome
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguardhome
                port:
                  number: 3000
    {{- end }}
  tls:
    - secretName: adguardhome-tls
      hosts:
        {{- range $host := .Values.ingress.hosts }}
        - {{ tpl $host $ }}
        {{- end }}
