- name: Copy config file
  template:
    src: ../files/client_{{ class }}.hcl
    dest: /etc/nomad.d/client.hcl
    mode: '0644'

- name: Copy systemd config file
  copy:
    src: ../files/nomad-client.service
    dest: /lib/systemd/system/nomad-client.service
    owner: nomad
    group: nomad
    mode: '0644'

- name: Start nomad client
  systemd:
    daemon-reload: true
    state: restarted
    name: nomad-client
    enabled: true