---
- name: ArgoCD | Create Ingress
  kubernetes.core.k8s:
    state: "{{ argocd_action }}"
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: argocd
        namespace: "{{ argocd_k8s_namespace }}"
      spec:
        rules:
        - host: "argocd.dub1.bednarzak.com"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: argocd-server
                  port:
                    name: http
