---
- run_once: yes
  block:
    - name: ArgoCD | Download Kubernetes yaml file definition
      get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        dest: /tmp/argocd_install.yaml
        owner: root
        group: root
        mode: 0440

    - name: ArgoCD | Manage Kubernetes objects
      k8s:
        namespace: "{{ argocd_k8s_namespace }}"
        src: /tmp/argocd_install.yaml
        state: "{{ argocd_action }}"
  always:
    - name: ArgoCD | Clean installation
      file:
        path: /tmp/argocd_install.yaml
        state: absent
