name: Renovate

on:
  # Trigger on Dependency Dashboard issue updates
  issues:
    types: [opened, edited, reopened]

  # Run on schedule
  schedule:
    - cron: "0 6 * * 1" # Monday at 6 AM UTC

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "info"
        type: choice
        options:
          - info
          - debug
          - trace

  # Run when renovate config is updated
  push:
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
      - ".renovaterc"

env:
  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}

# Enhanced permissions for GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  actions: read
  checks: read
  statuses: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    # Run on all types, but if its issues, just on Dependency Dashboard
    if: |
      github.event_name != 'issues' ||
      contains(github.event.issue.title, 'Dependency Dashboard')
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
