name: Run site.yml

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: Cluster
        required: true

  push:
    branches: [main]
    paths:
      - "ansible/**"

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: ${{ fromJSON(github.event.inputs.cluster != '' && format('["{0}"]', github.event.inputs.cluster) || '["bet1"]') }}
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Checkout
        uses: actions/checkout@v5

      - name: Decrypt git-crypt
        uses: amplium/git-crypt-action@master
        with:
          # git-crypt export-key -- - | base64
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook \
            -i ./inventory/${{ matrix.cluster }}/hosts.ini \
            --private-key ../private_key.pem \
            site.yml
